Remove Cluster SA i Role from Operator and move to OLM
IBM/ibm-licensing-operator pull request #114
Opened 2020-09-02 15:57 UTC by arturobrzut

https://github.ibm.com/ibmprivatecloud/roadmap/issues/39757
Limit LS operator required permissions #39757

2020-09-03 08:02 UTC, SzymonKowalczyk approved these changes

2020-09-03 09:46 UTC, adamdyszy requested changes

2020-09-03 09:46 UTC, adamdyszy commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> -	for _, imagePullSecret := range expectedSA.ImagePullSecrets {
since no imagepullsecrets in sa, then they need to be added to deployment directly

2020-09-03 15:02 UTC, arturobrzut commented on pkg/resources/service/helper.go
> +const LicensingServciceAccount = "ibm-licensing-operator"
done

2020-09-04 08:03 UTC, arturobrzut commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> -	for _, imagePullSecret := range expectedSA.ImagePullSecrets {
ok

2020-09-04 13:37 UTC, adamdyszy approved these changes

2020-09-04 13:37 UTC, adamdyszy commented on deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
> +                    imagePullPolicy: Always
this should stay ifnotpresent in the csv

2020-09-04 13:37 UTC, adamdyszy commented on deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
> +                        value: quay.io/opencloudio/ibm-licensing:1.2.0
csv should have digests here, but only for releases so it can stay that way for now

2020-09-04 13:37 UTC, adamdyszy commented
/lgtm

2020-09-04 13:38 UTC, merged