Rhmp
IBM/ibm-licensing-operator pull request #198
Opened 2020-11-24 11:56 UTC by kmigielek

red hat marketplace changes

2020-12-09 05:00 UTC, kmigielek commented
/retest

2020-12-14 11:46 UTC, arturobrzut requested changes

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/helper.go
> +	"github.com/cloudflare/cfssl/log"
can you removed this log ? cloudflare ?

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/helper.go
> +func UpdateServiceMonitor(reqLogger *logr.Logger, client c.Client, expected, found *monitoringv1.ServiceMonitor) (reconcile.Result, error) {
can you move it to servicemonitor file

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/helper.go
> +	IsRHMP = checkRHMPPrereqs(client)
why this is check?

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/services.go
> +	return "license-service-prometheus"
set all constant name  in helpers

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/services.go
> +	labels["release"] = "ibm-licensing-service-promethus"
set all constant name in helpers

2020-12-14 11:46 UTC, arturobrzut commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +			&monitoringv1.ServiceMonitor{},
add to csv and role yaml permision for service monitor

2020-12-14 11:46 UTC, arturobrzut commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +			&extensionsv1.NetworkPolicy{},
add to csv 1.4.X and role yaml permision for network policy

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/helper.go
> +	prometheus := &apiextensionv1beta1.CustomResourceDefinition{}
Reconsider checking all CRD vs checking the exact CRD 
it means or you add permission to list all CRD (in yaml role and csv)
or add permission to read / write service monitor or other CRD
send this to open slack channel Xteam or to me, @pgodowski @ab-ibm for agreement for it

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/networking.go
> +			"prometheus": "rhm-marketplaceconfig-meterbase",
add it to helper as const or var

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/networking.go
> +			"openshift.io/cluster-monitoring": "true",
add it to helper as const or var

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/networking.go
> +			"app": "ibm-licensing-service-instance",
add it to helper as const or var

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/service_monitor.go
> +					Path:       "/metrics",
recheck if Path /metrics is default , if yes remove this line

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/service_monitor.go
> +				"marketplace.redhat.com/metering": "true",
add it to helper as const or var

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/service/service_monitor.go
> +	return "license-service-service-monitor"
add it to helper as const or var

2020-12-14 11:46 UTC, arturobrzut commented on pkg/resources/helper.go
> +	IsRHMP = checkRHMPPrereqs(client)
only for log?

2020-12-14 11:46 UTC, arturobrzut commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +		reqLogger.Info("RHMP disabled or prometheus crd not present on cluster")
if RHMP is disabled to not log in INFO 
if RHMP is enabled but CRD for RHMP does not exist then maybe you can add WARN log

2020-12-14 11:46 UTC, arturobrzut commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +			&extensionsv1.NetworkPolicy{},
and probably we do not want to watch NetworkPolicy

2020-12-14 11:46 UTC, arturobrzut commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +			&monitoringv1.ServiceMonitor{},
and we probably do not want to watch ServiceMonitor

2020-12-15 18:40 UTC, kmigielek commented on pkg/resources/service/services.go
> +func GetServiceMonitor(instance *operatorv1alpha1.IBMLicensing) *monitoringv1.ServiceMonitor {
moved to new file

2020-12-15 18:41 UTC, kmigielek commented on pkg/resources/service/services.go
> +					Interval:   "15s",
I removed it and it got changed to default

2020-12-15 18:41 UTC, kmigielek commented on pkg/resources/service/services.go
> +					Scheme:     "https",
There is new logic to manage scheme

2020-12-15 18:41 UTC, kmigielek commented on pkg/resources/service/services.go
> +						InsecureSkipVerify: true,
There is new logic to manage ssl

2020-12-15 18:42 UTC, kmigielek commented on pkg/resources/helper.go
> +	"github.com/cloudflare/cfssl/log"
removed

2020-12-15 18:42 UTC, kmigielek commented on pkg/resources/service/networking.go
> +			"app": "ibm-licensing-service-instance",
moved to consts

2020-12-15 18:42 UTC, kmigielek commented on pkg/resources/service/service_monitor.go
> +					Path:       "/metrics",
by default there is ""

2020-12-15 18:42 UTC, kmigielek commented on pkg/resources/service/service_monitor.go
> +				"marketplace.redhat.com/metering": "true",
moved to consts

2020-12-15 18:44 UTC, kmigielek commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +			&monitoringv1.ServiceMonitor{},
service monitor is already added to role. Watcher removed

2020-12-15 18:44 UTC, kmigielek commented on pkg/resources/service/service_monitor.go
> +	return "license-service-service-monitor"
moved to consts

2020-12-15 18:44 UTC, kmigielek commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +		reqLogger.Info("RHMP disabled or prometheus crd not present on cluster")
log removed

2020-12-15 18:47 UTC, kmigielek commented on pkg/resources/helper.go
> +func UpdateServiceMonitor(reqLogger *logr.Logger, client c.Client, expected, found *monitoringv1.ServiceMonitor) (reconcile.Result, error) {
I left it there because there is function which checks services as well

2020-12-15 18:47 UTC, kmigielek commented on pkg/resources/helper.go
> +	IsRHMP = checkRHMPPrereqs(client)
It got change so function got removed

2020-12-15 18:48 UTC, kmigielek commented on pkg/resources/service/services.go
> +	return "license-service-prometheus"
moved to consts

2020-12-15 18:48 UTC, kmigielek commented on pkg/controller/ibmlicensing/ibmlicensing_controller.go
> +			&extensionsv1.NetworkPolicy{},
watcher removed and network policy permissions added

2020-12-15 18:49 UTC, kmigielek commented on pkg/resources/helper.go
> +	prometheus := &apiextensionv1beta1.CustomResourceDefinition{}
it got changed so we check only if there is any instance of MarketplaceConfig

2020-12-15 18:49 UTC, kmigielek commented on pkg/resources/service/networking.go
> +			"prometheus": "rhm-marketplaceconfig-meterbase",
moved to consts

2020-12-15 18:49 UTC, kmigielek commented on pkg/resources/service/networking.go
> +			"openshift.io/cluster-monitoring": "true",
moved to consts

2020-12-16 09:51 UTC, adamdyszy approved these changes

2020-12-16 10:40 UTC, arturobrzut approved these changes

2020-12-16 10:41 UTC, arturobrzut commented
/lgtm

2020-12-16 10:41 UTC, merged