use kubernetes.io/arch label
IBM/ibm-licensing-operator pull request #200
Opened 2020-11-25 09:46 UTC by adamdyszy

2020-11-25 09:50 UTC, pgodowski commented
We put this item on hold at least till Monday Nov 30th, unless further notice

2020-11-25 09:53 UTC, SzymonKowalczyk requested changes
Do not deliver/merge until final decision

2020-11-29 11:13 UTC, arturobrzut commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
@pgodowski @adamdyszy 
This change drop support for OCP 3.X, and for all k8s less than 1.13 (December 2018)
kubernetes.io/arch was added to k8s in 1.13 Release  December 2018
 * OCP 3.11 use Kubernetes 1.11 (last release 3.X)
 * OCP 4.1 use Kubernetes 1.13 (first release 4.X)

2020-11-29 11:15 UTC, arturobrzut commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
https://github.com/kubernetes/kubernetes/blob/release-1.12/pkg/kubelet/apis/well_known_labels.go
https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/kubelet/apis/well_known_labels.go

2020-12-21 08:51 UTC, pgodowski commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
@arturobrzut on OCP 3.11, do we install LS via OLM, or by direct deployment of the operator?

2021-02-04 09:29 UTC, pgodowski commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
what is the latest on this? @adamdyszy

2021-02-04 11:06 UTC, adamdyszy commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
@pgodowski we install without OLM

2021-02-04 14:15 UTC, pgodowski commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
can we merge then?

2021-02-05 17:58 UTC, arturobrzut commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
@pgodowski 
we can merge it (if we do not support releases OCP less then 4.1)

@pgodowski Can we confirm it 
Then I will merge it

@SzymonKowalczyk only need to resolve his reviewu

2021-02-15 08:22 UTC, pgodowski commented on deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
> -                            - key: beta.kubernetes.io/arch
@arturobrzut @adamdyszy please followup - I see references to `beta.kubernetes.io` in few other places including deployment.go

2022-08-09 12:10 UTC, closed without merging