remove digest from operator
IBM/ibm-licensing-operator pull request #208
Opened 2020-12-02 14:48 UTC by arturobrzut

2020-12-02 15:10 UTC, arturobrzut commented
The error in operator log if env variable will not be set
`{"level":"error","ts":1606920792.160643,"logger":"cmd","msg":"Operand environment variables not set correctly.","error":"ENV variable: OPERAND_LICENSING_IMAGE should have registry and image separated with \"/\" symbol","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/home/runner/work/ibm-licensing-operator/ibm-licensing-operator/cmd/manager/main.go:117\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/proc.go:204"}`

2020-12-02 15:30 UTC, adamdyszy requested changes

2020-12-02 15:30 UTC, adamdyszy commented on pkg/apis/operator/v1alpha1/helper.go
> +	if err := c.getImageParametersFromEnv("OPERAND_LICENSING_IMAGE"); err != nil {
refactor OPERAND_LICENSING_IMAGE, and other operand images into variables, as they are used couple of times

2020-12-02 15:30 UTC, adamdyszy commented on pkg/apis/operator/v1alpha1/helper.go
> +	if err := spec.setContainer("OPERAND_LICENSING_IMAGE"); err != nil {
refactor OPERAND_LICENSING_IMAGE, and other operand images into variables, as they are used couple of times

2020-12-02 16:56 UTC, arturobrzut commented on pkg/apis/operator/v1alpha1/helper.go
> +	if err := spec.setContainer("OPERAND_LICENSING_IMAGE"); err != nil {
done

2020-12-02 16:56 UTC, arturobrzut commented on pkg/apis/operator/v1alpha1/helper.go
> +	if err := c.getImageParametersFromEnv("OPERAND_LICENSING_IMAGE"); err != nil {
done

2020-12-08 15:49 UTC, adamdyszy approved these changes

2020-12-08 15:49 UTC, adamdyszy commented
/lgtm

2020-12-08 15:59 UTC, merged