Update readme
IBM/ibm-licensing-operator pull request #230
Opened 2020-12-14 13:39 UTC by ab-ibm

2021-02-05 16:55 UTC, pgodowski requested changes

2021-02-05 16:55 UTC, pgodowski commented on README.md
> +# License
please also update the top-level `LICENSE` file.

2021-03-26 13:56 UTC, SzymonKowalczyk approved these changes

2021-03-26 13:57 UTC, SzymonKowalczyk commented
@ab-ibm please check @pgodowski comment

2021-03-26 14:00 UTC, ab-ibm commented
@SzymonKowalczyk already resolved, LICENSE has this additional information at the bottom

2022-08-09 12:10 UTC, closed without merging