Add Usage container
IBM/ibm-licensing-operator pull request #281
Opened 2021-01-27 01:40 UTC by kacperkrzyzak

2021-01-27 11:06 UTC, arturobrzut requested changes
Can you add the test 
inside 
github.com/IBM/ibm-licensing-operator/controllers/ibmlicensing_controller_test.go
or in bats
In my option better will be inside go file test
which set CR with enabled this feature

2021-01-27 16:56 UTC, kacperkrzyzak commented
@arturobrzut added tests

2021-01-28 10:41 UTC, arturobrzut approved these changes

2021-01-28 10:41 UTC, arturobrzut commented
/lgtm

2021-01-28 10:41 UTC, merged