Added possibility to disable RHMP
IBM/ibm-licensing-operator pull request #286
Opened 2021-01-29 12:50 UTC by kmigielek

gracefully removes k8s resources which are related to rhmp when it gets disabled

2021-01-29 14:48 UTC, kacperkrzyzak requested changes

2021-01-29 14:48 UTC, kacperkrzyzak commented on controllers/resources/service/services.go
> +		return
Add usage Service to notExpected for disabled Usage

2021-01-29 16:51 UTC, kmigielek commented on controllers/resources/service/services.go
> +		return
its added to notExpected before return

2021-02-01 09:55 UTC, arturobrzut approved these changes

2021-02-01 09:56 UTC, arturobrzut commented
/lgtm

2021-02-01 10:20 UTC, closed without merging

2021-02-01 10:21 UTC, arturobrzut commented
open new PR 
kacper on vacation