coverage on ocp
IBM/ibm-licensing-operator pull request #293
Opened 2021-02-07 16:40 UTC by arturobrzut

2021-02-08 09:10 UTC, pgodowski requested changes

2021-02-08 09:10 UTC, pgodowski commented on controllers/ibmlicenseservicereporter_controller_test.go
> +			//			By("Checking status of the IBMLicensing")
avoid commented code, thanks!

2021-02-08 22:30 UTC, arturobrzut commented on controllers/ibmlicenseservicereporter_controller_test.go
> +			//			By("Checking status of the IBMLicensing")
ok , now I turn off test on KinD (k8s)
still test will work on OCP
on K8s I got Warning Failed    3m6s (x7 over 5m10s) kubelet           Error: container has runAsNonRoot and image will run as root

2021-02-09 07:47 UTC, pgodowski approved these changes

2021-02-09 07:48 UTC, pgodowski approved these changes

2021-02-09 07:49 UTC, pgodowski commented
/lgtm

2021-02-09 07:49 UTC, merged