update_channel
IBM/ibm-licensing-operator pull request #337
Opened 2021-03-25 12:11 UTC by antyona

2021-03-25 13:08 UTC, SzymonKowalczyk commented
Please do not merge before merge development to master !!!

2021-03-25 13:08 UTC, SzymonKowalczyk requested changes
Please wait until merge development to master!

2021-03-25 13:15 UTC, arturobrzut commented
or add PR do developement branch

2021-03-26 13:59 UTC, SzymonKowalczyk approved these changes

2021-03-26 14:01 UTC, SzymonKowalczyk commented
/lgtm

2021-03-26 14:05 UTC, merged