Update version.go
IBM/ibm-licensing-operator pull request #429
Opened 2021-07-16 09:10 UTC by marcin-ozog

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48302

2021-07-16 09:21 UTC, SzymonKowalczyk requested changes
Please review old commit: https://github.com/IBM/ibm-licensing-operator/commit/245526930c1a924bf32bd1137034d84da03004b2

2021-07-16 10:11 UTC, SzymonKowalczyk requested changes
You forgot to update db version - required for UBI currency automation

2021-07-16 10:11 UTC, SzymonKowalczyk commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
>                          value: quay.io/opencloudio/ibm-postgresql:12.0.7
set value to 12.0.8

2021-07-16 10:11 UTC, SzymonKowalczyk commented on config/manager/manager.yaml
>                value: quay.io/opencloudio/ibm-postgresql:12.0.7
set value to 12.0.8

2021-07-16 12:02 UTC, marcin-ozog commented on config/manager/manager.yaml
>                value: quay.io/opencloudio/ibm-postgresql:12.0.7
thanks, updated

2021-07-16 12:16 UTC, SzymonKowalczyk approved these changes

2021-07-16 13:20 UTC, kacperkrzyzak requested changes

2021-07-16 13:20 UTC, kacperkrzyzak commented on Makefile
>  OLD_CSV_VERSION ?= 1.5.0
Update old csv version to 1.6.0 and postgres image version

2021-07-16 13:20 UTC, kacperkrzyzak commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
>    replaces: ibm-licensing-operator.v1.5.0
Update replaces to 1.6.0

2021-07-16 13:31 UTC, marcin-ozog commented on Makefile
>  OLD_CSV_VERSION ?= 1.5.0
done

2021-07-19 07:25 UTC, marcin-ozog commented
/lgtm

2021-07-19 07:41 UTC, kacperkrzyzak approved these changes

2021-07-19 07:41 UTC, kacperkrzyzak commented
/lgtm

2021-07-19 07:42 UTC, merged