Update 1.8.0
IBM/ibm-licensing-operator pull request #447
Opened 2021-08-16 12:03 UTC by kacperkrzyzak

2021-08-16 12:48 UTC, SzymonKowalczyk requested changes

2021-08-16 12:48 UTC, SzymonKowalczyk commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +                        value: quay.io/opencloudio/ibm-postgresql:12.0.9
Please change postrges to 1.8.0

2021-08-16 12:48 UTC, SzymonKowalczyk commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +      image: quay.io/opencloudio/ibm-postgresql:12.0.9
Please change postrges to 1.8.0

2021-08-16 12:48 UTC, SzymonKowalczyk commented on config/manager/manager.yaml
> +              value: quay.io/opencloudio/ibm-postgresql:12.0.9
Please change postrges to 1.8.0

2021-08-16 16:32 UTC, kacperkrzyzak commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +                        value: quay.io/opencloudio/ibm-postgresql:12.0.9
The current version for Postgres is 12.0.9
Do we want to change versioning strategy for our Postgres image?

2021-08-17 09:52 UTC, SzymonKowalczyk commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +                        value: quay.io/opencloudio/ibm-postgresql:12.0.9
We agree with @pgodowski to have all the operand images in the same version

2021-08-17 10:40 UTC, kacperkrzyzak commented
/retest

2021-08-17 11:05 UTC, SzymonKowalczyk approved these changes

2021-08-17 11:05 UTC, SzymonKowalczyk commented
/lgtm

2021-08-17 11:05 UTC, merged