Automatic RHMP integration
IBM/ibm-licensing-operator pull request #533
Opened 2021-12-14 19:07 UTC by Niflhem

2021-12-14 19:47 UTC, kacperkrzyzak commented
I think you can also add logging of RHMP feature status here: controllers/ibmlicenseservicereporter_controller.go:478

2021-12-14 19:50 UTC, kacperkrzyzak approved these changes

2021-12-14 20:18 UTC, pgodowski requested changes

2021-12-14 20:18 UTC, pgodowski commented on controllers/resources/helper.go
> +		RHMPEnabled = true
Pls add status

2021-12-20 10:15 UTC, Niflhem commented on controllers/resources/helper.go
> +		RHMPEnabled = true
Fixed here https://github.com/IBM/ibm-licensing-operator/pull/533/commits/cd680066c47a857698c0574d044642aa2319b1cf

2021-12-20 13:04 UTC, adamdyszy approved these changes

2021-12-20 13:04 UTC, adamdyszy commented
/lgtm

2021-12-20 13:04 UTC, merged