update 1.13
IBM/ibm-licensing-operator pull request #553
Opened 2022-02-04 12:55 UTC by martabereta

2022-02-04 12:59 UTC, kacperkrzyzak requested changes

2022-02-04 12:59 UTC, kacperkrzyzak commented on README.md
> +- 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.2, 1.2.3, 1.3.1, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.13.0
Please add here 1.13 instead of replacing 1.12

2022-02-04 12:59 UTC, kacperkrzyzak commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +    operators.operatorframework.io/builder: operator-sdk-v1.12.0
Let's leave builder annotation as v1.11.0

2022-02-04 13:09 UTC, SzymonKowalczyk commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +    operators.operatorframework.io/builder: operator-sdk-v1.12.0
we do not update `operator-sdk-v1`

2022-02-07 11:00 UTC, kacperkrzyzak approved these changes

2022-02-07 11:00 UTC, kacperkrzyzak commented
/lgtm

2022-02-07 11:01 UTC, merged