documentation updates for Tanzu
IBM/ibm-licensing-operator pull request #629
Opened 2022-07-13 10:29 UTC by antyona

@adamdyszy Can you please review the PR with the doc updates for Tanzu? 

Related to: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54227

2022-07-14 19:57 UTC, adamdyszy requested changes
one typo, apart from that everything good

2022-07-14 19:57 UTC, adamdyszy commented on docs/Content/Configuration.md
> +To get the load balancer IP, and set is as a variable, run the following command:
set it

2022-07-15 08:48 UTC, antyona commented on docs/Content/Configuration.md
> +To get the load balancer IP, and set is as a variable, run the following command:
Corrected 👍

2022-07-18 10:53 UTC, adamdyszy commented
/retest

2022-07-19 08:49 UTC, merged