Fix multiple instances CRs
IBM/ibm-licensing-operator pull request #716
Opened 2022-12-14 12:21 UTC by Jan-Olszowka

2022-12-14 13:17 UTC, pgodowski requested changes

2022-12-14 13:17 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +		reconcileResult, err := res.DeleteResource(&reqLogger, r.Client, instance) // #TODO always delete newly created instance
We MUST not remove the initial instance, but instead we should just ignore the 2nd (and any subsequent) one.
We MUST not remove CRs, but perhaps put something into its `.status`.

For this, we somehow need to track the existing operand against the initial CRs.

2022-12-15 13:52 UTC, Jan-Olszowka commented on controllers/ibmlicensing_controller.go
> +		reconcileResult, err := res.DeleteResource(&reqLogger, r.Client, instance) // #TODO always delete newly created instance
Thank you @pgodowski for the feedback, I will analyse possible solutions and address it.

2023-01-03 11:00 UTC, Jan-Olszowka commented
The algorithm is working as following:
check if CR's label exists (for eg. "ACTIVE" or "INACTIVE" is considered labeled)
--> if not labeled run function to add labels for every CR (based on creation date - only oldest one is marked as ACTIVE)
--> else (label exist) then check if should be ignored or reconciled: 
|
-----> if label == INACTIVE { end reconcilation }
-----> else (label == ACTIVE) { continue standard reconcilation flow }

2023-01-05 12:31 UTC, pgodowski requested changes

2023-01-05 12:31 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +	sort.SliceStable(ibmlicensingList.Items, func(i, j int) bool {
This does not cover the scenario where there are potentially two CRs: one auto-generated (self-generated) and one created by ODLM. We should prioritize the auto-generated one.

2023-01-05 12:31 UTC, pgodowski commented on bundle/manifests/operator.ibm.com_ibmlicensings.yaml
> +              state:
how about the upgrade scenario?

2023-01-05 12:31 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +func (r *IBMLicensingReconciler) detectIBMLicensingState(ibmlicensingList *operatorv1alpha1.IBMLicensingList, reqLogger logr.Logger) (reconcile.Result, error) {
This function does not only '_detect_', but also modifies the oldest CR.
So, the function name shall be different than `detectIBMLicensingState`.

2023-01-09 08:17 UTC, Jan-Olszowka commented on controllers/ibmlicensing_controller.go
> +	initialInstance := ibmlicensingList.Items[0]
Added extra check to avoid issues in case of empty/null list.
```	
if ibmlicensingList.Items == nil || len(ibmlicensingList.Items) == 0 {
  return reconcile.Result{}, nil
}
```

2023-01-09 08:21 UTC, Jan-Olszowka commented on controllers/ibmlicensing_controller.go
> +func (r *IBMLicensingReconciler) detectIBMLicensingState(ibmlicensingList *operatorv1alpha1.IBMLicensingList, reqLogger logr.Logger) (reconcile.Result, error) {
Maybe something like `findAndMarkActiveIBMLicensing`?

2023-01-09 10:38 UTC, Jan-Olszowka commented on controllers/ibmlicensing_controller.go
> +			// extra check not to trigger reconciliation on inactive CRs
Correct, changed a comment to be more clear: 
`// CR should be marked as 'inactive' and ignored during next reconciliation`

2023-01-09 10:47 UTC, Jan-Olszowka commented on controllers/ibmlicensing_controller.go
> +		if cr.ObjectMeta.CreationTimestamp.Time.Equal(initialInstance.ObjectMeta.CreationTimestamp.Time) {
Yes it's edge case, however as correctly said, we can compare Kubernetes UIDs as we are always looking for one object during the loop check. Changed to:
`if cr.UID == initialInstance.UID`

2023-01-09 13:35 UTC, Jan-Olszowka commented on controllers/ibmlicensing_controller.go
> +	sort.SliceStable(ibmlicensingList.Items, func(i, j int) bool {
This will be addressed in separated epic @adamdyszy @pgodowski

2023-01-10 12:05 UTC, adamdyszy approved these changes

2023-01-10 12:05 UTC, adamdyszy commented on controllers/ibmlicensing_controller.go
> +	sort.SliceStable(ibmlicensingList.Items, func(i, j int) bool {
this case is not addressed yet in existing epic, needs discussion

2023-01-10 12:48 UTC, merged