add default reader token to support k8s 1.24+
IBM/ibm-licensing-operator pull request #741
Opened 2023-01-19 13:55 UTC by adamdyszy

2023-01-19 14:23 UTC, SzymonKowalczyk approved these changes

2023-01-19 15:26 UTC, pgodowski requested changes

2023-01-19 15:26 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +			reqLogger.Error(err, "Failed to delete ServiceAccount secret due to wrong annotations.")
which Secret was failed to be removed?
(missing secret name in the error log entry)

2023-01-19 15:26 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +		reqLogger.Info("Failed to get expected secret")
not verbose enough - the reader of this log entry wouldn't understand this

2023-01-19 15:26 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +		foundSecret.Annotations[service.ServiceAccountSecretAnnotationKey] {
What is the risk that we might be accidentally removing some other Secret?

2023-01-25 15:20 UTC, adamdyszy commented on controllers/ibmlicensing_controller.go
> +			reqLogger.Error(err, "Failed to delete ServiceAccount secret due to wrong annotations.")
the secret name is build into reqLogger at the start of this method function

2023-01-25 15:31 UTC, adamdyszy commented on controllers/ibmlicensing_controller.go
> +		reqLogger.Info("Failed to get expected secret")
reconcilation loop below will return full err and this would produce more verbose log in parent functions

2023-01-26 04:48 UTC, adamdyszy commented
/retest

2023-01-27 13:06 UTC, geforcelive commented
/lgtm

2023-01-27 13:11 UTC, merged