licenseAccept added to CR
IBM/ibm-licensing-operator pull request #789
Opened 2023-04-25 06:44 UTC by martabereta

2023-05-09 13:36 UTC, jakubsolecki approved these changes

2023-05-09 14:14 UTC, PiotrWodecki requested changes

2023-05-09 14:14 UTC, PiotrWodecki commented on controllers/ibmlicensing_controller_test.go
> +			}, timeout, interval).Should(Equal(false))
Please remove duplicate test and consider in which test group it should be placed.

2023-05-09 14:14 UTC, PiotrWodecki commented on controllers/resources/service/containers.go
> +	}
Please remove this environment variable, it's not used by this container.

2023-05-10 09:41 UTC, PiotrWodecki commented
/lgtm

2023-05-10 09:43 UTC, merged