Add sender certificates secret volume configuration
IBM/ibm-licensing-operator pull request #912
Opened 2024-05-17 10:17 UTC by Jan-Olszowka

2024-05-20 08:19 UTC, Jan-Olszowka commented
s390x targets fail for no reason - prow problems again i guess.

2024-05-20 09:46 UTC, jakubsolecki requested changes

2024-05-20 09:46 UTC, jakubsolecki commented on controllers/resources/service/volumes.go
> +					MountPath: "/opt/reporter/certs",
Let's keep all the data used by sender module in one place. We already have reporter token in `/opt/ibm/licensing`, so let's also have there reporter certs, named like `reporter-certs`.

Alternatively, reporter token might be moved to `/opt/ibm/reporter` but that would require a lot of testing to ensure such change is fully backward compatible.

2024-05-20 09:46 UTC, jakubsolecki commented on api/v1alpha1/ibmlicensing_types.go
> +	ReporterCertsSecretName string `json:"reporterCertsSecretName,omitempty"`
I'd opt for `ReporterCertsSecret` just to be consistent with the existing parameter named `ReporterSecretToken`.

2024-05-20 10:38 UTC, Jan-Olszowka commented on api/v1alpha1/ibmlicensing_types.go
> +	ReporterCertsSecretName string `json:"reporterCertsSecretName,omitempty"`
I agree it would be consistent but it's very misleading - this is not secret itself, it's just a name of secret resource on cluster. I personally was confused by the `ReporterSecretToken` which I though is token itself and I need to further investigate underlying logic to see that it is a name of the token. I wouldn't opt to also make same issue here

2024-05-20 10:52 UTC, Jan-Olszowka commented on controllers/resources/service/volumes.go
> +					MountPath: "/opt/reporter/certs",
Addressed in latest commit [5611694](https://github.com/IBM/ibm-licensing-operator/pull/912/commits/561169499b8692c157f52a1089882c692127e0a2)

2024-05-20 11:07 UTC, jakubsolecki commented on api/v1alpha1/ibmlicensing_types.go
> +	ReporterCertsSecretName string `json:"reporterCertsSecretName,omitempty"`
After further consideration I agree with you. I was initially too focused solely on consistency.

2024-05-20 12:34 UTC, kflorianski-ibm commented on controllers/resources/service/volumes.go
> +					MountPath: "/opt/reporter/certs",
Also, can we move mount path to a const?

2024-05-20 12:38 UTC, kflorianski-ibm requested changes

2024-05-20 12:38 UTC, kflorianski-ibm commented on controllers/resources/service/volumes.go
> +		reporterCertsSecretName := spec.Sender.ReporterCertsSecretName
I don't think having this variable is necessary, can we use `spec.Sender.ReporterCertsSecretName` directly?

2024-05-20 12:38 UTC, kflorianski-ibm commented on controllers/resources/service/volumes.go
> +			reporterHTTPSCertSecretVolume := corev1.Volume{
There is also no need to have `reporterHTTPSCertSecretVolume` variable, you could use an `append` statement the same way you have done with the volume mount

2024-05-20 12:38 UTC, kflorianski-ibm commented on controllers/resources/service/volumes.go
> +					MountPath: "/opt/reporter/certs",
Can we move mount path to const?

2024-05-20 23:28 UTC, ljeda approved these changes
I have one small optional remark. apart from other guys comments, looks good, thanks :)

2024-05-20 23:28 UTC, ljeda commented on api/v1alpha1/ibmlicensing_types.go
> +	// Name of the License Service Reporter secret that contains internal certificates used to establish secure connection. You need to create it in instance namespace
I wouldn't call it "License Service Reporter secret", because this makes me thinking that this secret is owned by LSR while this is supposed to be the (manually created) copy of the LSR-owned secret. I would vote for "Name of the secret that contains the License Service Reporter certificate(s) used for establishing a secure connection with it. You need to create it in instance namespace"

2024-05-21 07:21 UTC, Jan-Olszowka commented on controllers/resources/service/volumes.go
> +					MountPath: "/opt/reporter/certs",
We can but them we would have to move every other path from volumes that is not const. Do we want to do it in context of these issue? Of course I can do it but should it be done for every mountPath that we have from different features?

2024-05-21 07:21 UTC, Jan-Olszowka commented on controllers/resources/service/volumes.go
> +		reporterCertsSecretName := spec.Sender.ReporterCertsSecretName
Right - I didn't want to use spec.Sender.ReporterCertsSecretName twice but this is also variable, not function so it can be used. I will change it.

2024-05-21 07:21 UTC, Jan-Olszowka commented on controllers/resources/service/volumes.go
> +			reporterHTTPSCertSecretVolume := corev1.Volume{
I agree, variable will be removed, append here can be used as you pointed but I think to be consistent I would have to also change other volumes created here to be just appended.

2024-05-21 07:21 UTC, Jan-Olszowka commented on api/v1alpha1/ibmlicensing_types.go
> +	// Name of the License Service Reporter secret that contains internal certificates used to establish secure connection. You need to create it in instance namespace
Right, I agree and will change it, thanks Jedi :)

2024-05-21 07:31 UTC, Jan-Olszowka commented on api/v1alpha1/ibmlicensing_types.go
> +	// Name of the License Service Reporter secret that contains internal certificates used to establish secure connection. You need to create it in instance namespace
Addressed in [6defa93](https://github.com/IBM/ibm-licensing-operator/pull/912/commits/6defa93df91b8aae8d166f3281dd1028c72dd6b8)

2024-05-21 07:32 UTC, Jan-Olszowka commented on controllers/resources/service/volumes.go
> +		reporterCertsSecretName := spec.Sender.ReporterCertsSecretName
Addressed in [054b4d4](https://github.com/IBM/ibm-licensing-operator/pull/912/commits/054b4d45d213f33cf888ea1a41941bc0beb8a1ff)

2024-05-21 07:33 UTC, Jan-Olszowka commented on controllers/resources/service/volumes.go
> +			reporterHTTPSCertSecretVolume := corev1.Volume{
Addressed in [054b4d4](https://github.com/IBM/ibm-licensing-operator/pull/912/commits/054b4d45d213f33cf888ea1a41941bc0beb8a1ff), here I also did same thing to rest of volumes.

2024-05-21 08:07 UTC, kflorianski-ibm commented on controllers/resources/service/volumes.go
> +					MountPath: "/opt/reporter/certs",
I think so, it's a reasonable refactor for this PR I'd say. At least in this `volumes.go` file.

2024-05-21 21:55 UTC, ljeda approved these changes
looks good, thanks :)

2024-05-22 09:29 UTC, kflorianski-ibm requested changes
Missing test cases:
- `spec.Sender.ValidateReporterCerts` is `false` and `ReporterCertsSecretName` is `some-cert-name` -> should not create volumes and mounts and should not set the `VALIDATE_REPORTER_CERTS ` env var
- `spec.Sender.ValidateReporterCerts` is `true` and `ReporterCertsSecretName` is not set (empty) -> should not create volumes and mounts, but should set the `VALIDATE_REPORTER_CERTS` env var

2024-05-22 13:10 UTC, kflorianski-ibm approved these changes

2024-05-28 11:01 UTC, jakubsolecki approved these changes

2024-06-06 10:00 UTC, merged