Added ingress class name option to avoid using deprecated annotation
IBM/ibm-licensing-operator pull request #913
Opened 2024-05-20 15:27 UTC by kflorianski-ibm

2024-05-23 13:38 UTC, Pejdzor requested changes

2024-05-23 13:38 UTC, Pejdzor commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +    containerImage: icr.io/cpopen/ibm-licensing-operator:4.2.4
why you bumped down image version?

2024-05-23 13:44 UTC, kflorianski-ibm commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +    containerImage: icr.io/cpopen/ibm-licensing-operator:4.2.4
Fixed in dd10f5d8d1b4168ab92d889358c2c8529ce33482

2024-05-23 13:52 UTC, Pejdzor approved these changes
Look's good to me :)

2024-05-23 13:53 UTC, Pejdzor commented
/approve

2024-05-23 13:54 UTC, Pejdzor commented
/lgtm

2024-05-26 20:27 UTC, ljeda approved these changes

2024-05-26 20:27 UTC, ljeda commented
does this item require any documentation changes?

2024-05-27 07:53 UTC, kflorianski-ibm commented
@ljeda Yes, I have them ready. Will prepare once tests for this are finished

2024-06-11 10:56 UTC, michalpaluch commented
approved

2024-06-19 08:28 UTC, Jan-Olszowka commented
/approve

2024-06-19 08:28 UTC, Jan-Olszowka commented
/lgtm

2024-06-19 08:28 UTC, merged