Switch from reflect.DeepEqual to Semantic.DeepEqual
IBM/ibm-licensing-operator pull request #918
Opened 2024-06-05 10:21 UTC by Pejdzor

golang reflect.DeepEqual() sometime returns false when comparing 2 semantically identical objects, so we switch from using this to Semantic.DeepEqual().

2024-06-05 15:30 UTC, Pejdzor commented
/retest

2024-06-06 20:39 UTC, ljeda requested changes
also, did you run any automation for these changes? no regression?

2024-06-06 20:39 UTC, ljeda commented on controllers/resources/helper.go
> -	"reflect"
why you remove this package but add it two lines above?

2024-06-07 12:50 UTC, Pejdzor commented on controllers/resources/helper.go
> -	"reflect"
Auto-refactoring from IDE, it moves imports between lines, if they suits more in other position.
In this situation it grouped built-in package imports above other (external) ones.

2024-06-08 18:04 UTC, ljeda approved these changes

2024-06-10 09:59 UTC, kflorianski-ibm approved these changes

2024-06-18 12:13 UTC, ljeda commented
/lgtm

2024-06-19 10:58 UTC, Jan-Olszowka commented
/approve

2024-06-19 11:09 UTC, Jan-Olszowka commented
/lgtm

2024-06-19 11:10 UTC, Jan-Olszowka commented
/approve

2024-06-19 11:10 UTC, merged