Remove usageBased container from LTSR operator
IBM/ibm-licensing-operator pull request #919
Opened 2024-06-05 12:25 UTC by Pejdzor

Remove usageBased Container Feature from License Service

2024-06-11 09:02 UTC, kflorianski-ibm commented
See https://github.com/IBM/ibm-licensing-operator/pull/916#pullrequestreview-2109800387

2024-06-11 22:46 UTC, ljeda requested changes

2024-06-11 22:46 UTC, ljeda commented on bundle/metadata/annotations.yaml
> +  operators.operatorframework.io.bundle.package.v1: ibm-licensing-operator
why we introduce this change here?

2024-06-12 07:03 UTC, Pejdzor commented on bundle/metadata/annotations.yaml
> +  operators.operatorframework.io.bundle.package.v1: ibm-licensing-operator
We are not supposed. I created 4 Pull Requests, and missed this. Good catch, thanks a lot

2024-06-12 09:59 UTC, kflorianski-ibm approved these changes

2024-06-16 15:24 UTC, ljeda approved these changes

2024-06-18 12:13 UTC, ljeda commented
/lgtm

2024-06-20 07:02 UTC, Jan-Olszowka commented
/approve

2024-06-20 07:02 UTC, Jan-Olszowka commented
/lgtm

2024-06-20 07:03 UTC, merged