61869 namespace scoping param
IBM/ibm-licensing-operator pull request #922
Opened 2024-06-26 12:40 UTC by alicenoknow

2024-07-03 10:35 UTC, kflorianski-ibm requested changes

2024-07-03 10:35 UTC, kflorianski-ibm commented on api/v1alpha1/features.go
> +	// Namespace denial limit for custom namespaces scoping
Please add to this docstring that this is the number of retrials

2024-07-03 10:36 UTC, kflorianski-ibm commented on api/v1alpha1/features.go
> +	// Namespace denial limit for custom namespaces scoping
Remember to re-generate bundle after this change

2024-07-03 12:00 UTC, Jan-Olszowka commented on api/v1alpha1/features.go
> +	// +operator-sdk:csv:customresourcedefinitions:type=spec,xDescriptors="urn:alm:descriptor:com.tectonic.ui:hidden"
Should this field's descriptor be hidden on OCP UI? `descriptor:com.tectonic.ui:hidden` There will be no way to modify it from UI when creating CR.

2024-07-03 12:02 UTC, alicenoknow commented on api/v1alpha1/features.go
> +	// +operator-sdk:csv:customresourcedefinitions:type=spec,xDescriptors="urn:alm:descriptor:com.tectonic.ui:hidden"
Yes, that's intended. This field should be used only for testing purposes.

2024-07-03 12:18 UTC, Jan-Olszowka approved these changes

2024-07-08 06:36 UTC, kflorianski-ibm approved these changes

2024-07-22 12:31 UTC, kflorianski-ibm commented
/lgtm

2024-07-22 12:32 UTC, merged