Workaround for controller-filtered-cache flaw test
IBM/ibm-licensing-operator pull request #932
Opened 2024-09-13 10:07 UTC by alicenoknow

2024-09-16 11:04 UTC, alicenoknow commented
### Test input

1. Prepare a cluster with [IBM Cloud Pak foundational services](https://ibmdocs-test.dcs.ibm.com/docs/en/cloud-paks/foundational-services) and License Service installed and configured.
2. Create a namespace e.g. `test-ns`
3. Create an OperandRequest for created namespace
```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: test-operand-request
  namespace: test-ns
spec:
  requests:
    - operands:
        - name: ibm-licensing-operator
      registry: common-service
```

4. Wait until LS operator discovers the request, create secrets/configmaps in that namespace and updates `targetNamespaces`. The operator will restart afterwards automatically.

5. Remove the test namespace
6. Wait until the cleaner task is run (in a meantime during the reconciliation the errors about missing namespace will appear)
7. The task should clean missing namespace from `targetNamespaces` inside OperatorGroup and restart LS operator pod

2024-09-16 12:56 UTC, ljeda requested changes

2024-09-16 12:56 UTC, ljeda commented on controllers/operatorgroup_cleaner.go
> +			return false
we should either return `true` in order not to remove the namespace accidentally when we couldn't check its existence or (preferably) throw the error up to inform about the issue with the namespace existence checking.

2024-09-16 12:56 UTC, ljeda commented on controllers/operatorgroup_cleaner.go
> +		if strings.HasPrefix(operatorGroup.Name, "ibm-licensing-") {
are we sure this is a hardcoded name prefix?

my assumption would be that there should be only one `OperatorGroup` resource in the cluster. maybe we need to check that's the case and fail otherwise? need to check it.

2024-09-16 12:56 UTC, ljeda commented on controllers/operatorgroup_cleaner.go
> +			err := removeNamespaceFromOperatorGroup(logger, client, operatorNamespace, ns)
we should first gather the list of all the namespaces to remove, then remove them in one go, because otherwise we could not finish the loop before the OLM restarts the operator.

2024-09-16 12:56 UTC, ljeda commented on main.go
> +	go controllers.RunRemoveStaleNamespacesFromOperatorGroupTask(removeStaleNamespacesTaskCtx, &logger, mgr.GetClient(), mgr.GetAPIReader())
are we sure if this is going to work when we use the same `mgr` object that uses the blocking `cache.MultiNamespacedFilteredCacheBuilder` method? isn't here a race condition what will be first: the removal of the namespace or the problem with the cache library blocking further checks? or is it handled by the `context.Background()`?

2024-09-16 16:24 UTC, alicenoknow commented on main.go
> +	go controllers.RunRemoveStaleNamespacesFromOperatorGroupTask(removeStaleNamespacesTaskCtx, &logger, mgr.GetClient(), mgr.GetAPIReader())
the cache is not blocking it just throws errors from time to time, but does not block other goroutines execution. Also as per documentation the `APIReader` should not use the cache, but API directly.

2024-09-18 10:00 UTC, ljeda requested changes

2024-09-18 10:00 UTC, ljeda commented on main.go
> +	go controllers.RunRemoveStaleNamespacesFromOperatorGroupTask(removeStaleNamespacesTaskCtx, &logger, mgr.GetClient(), mgr.GetAPIReader())
OK, but we need to for sure move this block of code right after below line 199 (please look at the comment in line 191)

2024-09-18 10:00 UTC, ljeda commented on controllers/operatorgroup_cleaner.go
> +		if strings.HasPrefix(operatorGroup.Name, "ibm-licensing-") {
so my question is, why not to use mentioned method instead? moreover, the mentioned method does not rely on OG name prefix but on the prefix of the `olm.providedAPIs` field in the OG spec which makes more sense.

2024-09-19 07:18 UTC, pgodowski requested changes

2024-09-19 07:18 UTC, pgodowski commented on controllers/ibmlicensing_controller.go
> +// +kubebuilder:rbac:groups="",resources=namespaces,verbs=get
Is there a way to address the same goal, but without adding extra cluster permission to get namespaces?

2024-09-19 07:18 UTC, pgodowski commented on controllers/operatorgroup_cleaner.go
> +func removeStaleNamespacesFromOperatorGroup(logger *logr.Logger, client client.Client, reader client.Reader) {
OpertorGroup has two fields: `.spec` and `.status` - the `.status` is managed by OLM and keeps the list of current namespaces which are existing on the cluster and into which OLM projected RBAC already.

I feel that instead of ourselves doing the checking whether namespaces exist, we should make sure that .spec and .status of OperatorGroup is kept in sync.

2024-09-19 09:39 UTC, alicenoknow commented on controllers/operatorgroup_cleaner.go
> +func removeStaleNamespacesFromOperatorGroup(logger *logr.Logger, client client.Client, reader client.Reader) {
I've checked it and the behaviour is a bit different, its presented in following scenario:
1. LS working in `ibm-licensing`
```
OperatorGroup
---
spec:
  targetNamespaces:
    - ibm-licensing
status:
  namespaces:
    - ibm-licensing
```
2. Create namespace `ns-1` and add OperandRequest for it
3. OperatorGroup updates and adds `ns-1` both to `spec.targetNamespaces` and `status.namespaces`, bind info and RBACs are created
```
OperatorGroup
---
spec:
  targetNamespaces:
    - ibm-licensing
    - ns-1
status:
  namespaces:
    - ibm-licensing
    - ns-1
```
4. Remove `ns-1`
5. `olm-operator` reconciles but it does not updates namespaces, instead it keeps throwing
```
sync {"update" "ibm-licensing/ibm-licensing-operator.v4.2.8"} failed: bug: no target CSV for namespace ns-1
level=info msg="couldn't copy CSV to target namespaces" csv=ibm-licensing-operator.v4.2.8 error="bug: no target CSV for namespace ns-1" id=QlTHU namespace=ibm-licensing phase=Succeeded
```
6. Force update -> create new namespace `ns-2` and add new OperandRequest
7. OperatorGroup gets updated with `ns-2` but does not remove `ns-1`
```
OperatorGroup
---
spec:
  targetNamespaces:
    - ibm-licensing
    - ns-1
    - ns-2
status:
  namespaces:
    - ibm-licensing
    - ns-1
    - ns-2
```

2024-09-19 10:00 UTC, pgodowski commented on controllers/operatorgroup_cleaner.go
> +func removeStaleNamespacesFromOperatorGroup(logger *logr.Logger, client client.Client, reader client.Reader) {
You are right - seems that indeed OLM is not updating `.status` upon namespace removal.

2024-09-19 10:01 UTC, pgodowski approved these changes

2024-09-19 10:23 UTC, ljeda approved these changes

2024-09-19 10:24 UTC, ljeda commented
/lgtm

2024-09-19 10:28 UTC, merged