Add opreq status
IBM/ibm-licensing-operator pull request #939
Opened 2024-10-08 10:49 UTC by kflorianski-ibm

2024-10-08 11:27 UTC, Jan-Olszowka approved these changes

2024-10-09 18:58 UTC, ljeda approved these changes

2024-10-10 11:44 UTC, Jan-Olszowka requested changes

2024-10-10 11:44 UTC, Jan-Olszowka commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +    containerImage: icr.io/cpopen/ibm-licensing-operator:4.2.9
Do we want to downgrade operator version? I don't think so - 4.2.9 was already released.

2024-10-10 11:50 UTC, kflorianski-ibm commented on bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
> +    containerImage: icr.io/cpopen/ibm-licensing-operator:4.2.9
Ehhh, some merge-conflict resolution went wrong

2024-10-10 11:57 UTC, Jan-Olszowka approved these changes

2024-10-10 13:53 UTC, ljeda approved these changes

2024-10-17 11:51 UTC, Pejdzor commented
/meow

2024-10-17 11:52 UTC, Pejdzor commented
/woof

2024-10-17 11:52 UTC, Pejdzor commented
/aprove

2024-10-17 11:52 UTC, Pejdzor approved these changes
/lgtm

2024-10-17 11:53 UTC, Pejdzor commented
/honk

2024-10-17 11:53 UTC, merged