Reporting Interval as property in CustomResourceDefinition
IBM/ibm-licensing-operator pull request #940
Opened 2024-10-09 16:49 UTC by Pejdzor

2024-10-09 16:55 UTC, Pejdzor commented
/retest

2024-10-09 17:00 UTC, Pejdzor commented
/meow

2024-10-09 17:00 UTC, Pejdzor commented
/honk

2024-10-09 17:01 UTC, Pejdzor commented
/woof

2024-10-09 17:02 UTC, Pejdzor commented
/joke

2024-10-10 12:16 UTC, Pejdzor commented
/meow

2024-10-10 12:16 UTC, Pejdzor commented
/honk

2024-10-10 12:17 UTC, Pejdzor commented
/joke

2024-10-11 06:12 UTC, kflorianski-ibm requested changes
/meow

2024-10-11 06:12 UTC, kflorianski-ibm commented on api/v1alpha1/ibmlicensing_types.go
> +	WorkloadsReportingInterval string `json:"workloadsReportingInterval,omitempty"`
Please consider adding pattern validation. For k8s cron, this is what I added in the scanner operator:
```
// Frequency of the scans in the cron job format
// +kubebuilder:validation:Pattern:=`(@(annually|yearly|monthly|weekly|daily|midnight|hourly))|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})`
// +optional
Frequency string `json:"frequency,omitempty"`
```

2024-10-11 06:12 UTC, kflorianski-ibm commented on api/v1alpha1/ibmlicensing_types.go
> +	WorkloadsReportingInterval string `json:"workloadsReportingInterval,omitempty"`
The name is a bit lengthy (clients must type `workloadsReportingInterval`) but I don't have a better idea for now, so this comment is just "maybe a random idea will appear"

2024-10-11 06:12 UTC, kflorianski-ibm commented on api/v1alpha1/helper.go
> +
Unused, you use `spec.Sender.WorkloadsReportingInterval != ""` anyway (which is fine!). Remove the function plz

2024-10-11 06:12 UTC, kflorianski-ibm commented on controllers/resources/service/containers.go
> +					Value: "true",
Do we need both? Can't we have a check on the operand side if `SENDER_WORKLOADS_INTERVAL` empty then -> disabled (similarly to how the API value is being described - if not provided, the feature is disabled)

2024-10-11 06:12 UTC, kflorianski-ibm commented on controllers/resources/service/containers.go
> +		if spec.Sender.WorkloadsReportingInterval != "" {
Can you add a comment please -> "If workloads reporting feature is enabled, pass the env vars marking this to the operand" or something similar (for the entire code block).

2024-10-11 07:19 UTC, Pejdzor commented on api/v1alpha1/ibmlicensing_types.go
> +	WorkloadsReportingInterval string `json:"workloadsReportingInterval,omitempty"`
Sounds, better, thanks a lot

2024-10-11 07:20 UTC, Pejdzor commented on api/v1alpha1/ibmlicensing_types.go
> +	WorkloadsReportingInterval string `json:"workloadsReportingInterval,omitempty"`
And appeared

2024-10-16 12:02 UTC, kflorianski-ibm approved these changes

2024-10-21 15:53 UTC, ljeda commented
/lgtm

2024-10-21 15:53 UTC, ljeda commented
/meow

2024-10-21 15:53 UTC, merged

2024-12-05 13:06 UTC, Pejdzor commented
/honk

2024-12-05 13:06 UTC, Pejdzor commented
/woof