ILS-233 LS operator keeps restarting when there is OperandRequest in non-existent namespace
IBM/ibm-licensing-operator pull request #945
Opened 2024-10-31 11:42 UTC by alicenoknow

**Parent issue**: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/30974

**Bug:**
The LS operator keeps adding and removing namespace from OperatorGroup, which causes it to restart constantly.

**Why it happens:**
The issue persists because there is an OperandRequest in a non-existent namespace. Our OperandRequestController detects the OperandRequest and add its namespace to the OperatorGroup. We also have an async job which periodically runs and checks whether namespaces inside OperatorGroup exist (introduced here: https://github.com/IBM/ibm-licensing-operator/pull/932). The namespace is not present in the cluster, so we delete it from OperatorGroup, which triggers LS operator restart. The reason why there is an OperandRequest in a non-existent namespace is probably due to some finalisers issue and namespace force deletion, please see this comment: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/30974#issuecomment-95765457.
```
➜ oc get namespace rk-instance -o yaml
Error from server (NotFound): namespaces "rk-instance" not found

➜ oc get operandrequest --all-namespaces
NAMESPACE       NAME                                AGE     PHASE     CREATED AT
...
rk-instance     catalog-api-ibm-licensing-request   28d     Running   2024-10-01T14:54:27Z
rk-instance     ibm-iam-request                     29d     Running   2024-10-01T13:35:10Z
rk-instance     postgresql-operator-request         29d     Running   2024-10-01T13:36:56Z
rk-instance     zen-ca-operand-request              29d     Pending   2024-10-01T13:40:38Z
... 
```

**Solution**:
The possible solution is to add an extra check to OperandRequestController to verify whether the namespace exists before adding it to OperatorGroup. In general this check is not needed, it's only to prevent from such strange edge cases.

2024-10-31 11:53 UTC, pgodowski requested changes

2024-10-31 11:53 UTC, pgodowski commented on controllers/operandrequest_discovery.go
> +// It can happen that there is an OperandRequest in a non-existent namespace, which causes LS operator to restart constantly
```suggestion
// It can happen that there is an OperandRequest in a non-existent namespace, which causes LS operator to restart constantly. Such scenario was found when namespace was force delete, while OperandRequest had pending finalization due to removed Pod providing finalization logic
```

2024-10-31 12:02 UTC, kflorianski-ibm commented on controllers/operandrequest_discovery.go
> +			if !checkIfOperandRequestNamespaceIsValid(logger, reader, operandRequest) {
`!isOperandRequestNamespaceValid`

2024-10-31 12:03 UTC, kflorianski-ibm commented on controllers/operandrequest_discovery.go
> +// To prevent such case, we are additionally checking if the namespace actually exists when processing OperandRequests
Use block comments:
```
/*
...
*/
```

2024-10-31 12:04 UTC, kflorianski-ibm commented on controllers/operandrequest_discovery.go
> +// This check is added because of the edge case scenario which is described in: https://jsw.ibm.com/browse/ILS-233
We should describe the scenario here rather than link an issue. E.g. what if Jira is sunset? If all info already described then no need for this line.

2024-10-31 12:05 UTC, kflorianski-ibm commented on controllers/operandrequest_discovery.go
> +	if namespaceExists, err := namespaceExists(reader, operandRequest.Namespace); err != nil {
Avoid shadowing function name, call var e.g. `exists`

2024-10-31 12:06 UTC, kflorianski-ibm commented on controllers/operandrequest_discovery.go
> +		logger.Error(err, "Failed to check namespace existence: "+operandRequest.Namespace)
Use `Errorf` please

2024-10-31 12:07 UTC, kflorianski-ibm commented on controllers/operandrequest_discovery.go
> +	}
You can do this like so, so it's less confusing:
```
exists, err := namespaceExists(...)
if exists {
...
} else {
...
}
```

2024-10-31 12:24 UTC, alicenoknow commented on controllers/operandrequest_discovery.go
> +		logger.Error(err, "Failed to check namespace existence: "+operandRequest.Namespace)
logger doesn't support Errorf and I don't see a reason for packing this into Errorf and passing to logger in such form, will it provide better formatting or what's the reason?

2024-10-31 13:23 UTC, ljeda approved these changes

2024-10-31 14:05 UTC, kflorianski-ibm approved these changes

2024-11-05 14:45 UTC, ljeda commented
/lgtm

2024-11-05 14:46 UTC, merged

2024-12-05 15:29 UTC, filipio commented
/meow

2024-12-05 15:29 UTC, filipio commented
/woof