ILS-233 Add additional check to prevent adding terminating namespace to OperatorGroup
IBM/ibm-licensing-operator pull request #946
Opened 2024-11-05 14:50 UTC by alicenoknow

Follow-up to: https://github.com/IBM/ibm-licensing-operator/pull/945

Currently terminating namespace can be added by our `operandrequests-discovery` feature to the OpertorGroup. In such case operator cannot create bindings in that namespace and crashes.

2024-11-05 15:39 UTC, ljeda commented
just for the context, this is not really a real scenario as the normal scenario would be:
- Namespace gets created,
- OperandRequest gets created,
- LS creates bindings,
- Namespace gets removed (and it stucks in `Terminating` state for a while).

In such scenario I assume LS will not crash (at least immediately) as the bindings were already created.

Anyway, this is not a regression, so this does not need to be included in SC2 4.6.8.

2024-11-05 20:24 UTC, ljeda requested changes

2024-11-05 20:24 UTC, ljeda commented on controllers/operandrequest_discovery.go
> +	}
instead of adding second check and duplicating the code in `namespaceExists` and `namespaceActive` methods it would be better to extend/transform the `namespaceExists` into `namespaceActive` so that in the same method you would check for both existence and proper state. The `namespaceExists` method is used in only one more place which is a logical complement of what we're trying to achieve here (removal of namespace from OperatorGroup if we should stop syncing bindings to that namespace which exactly should happen also if namespace is in `Terminating` state as well).

2024-11-06 07:47 UTC, alicenoknow commented
### Test scenarios

1. OperandRequest from terminating namespace -> LS should not add namespace to OperatorGroup
2. Terminating namespace in OperatorGroup -> LS should remove namespace from OperatorGroup (job runs every 1h)
3. OperandRequest  from non-existing namespace -> LS should not add namespace to OperatorGroup
4. Non-existing namespace already in OperatorGroup -> LS should remove namespace from OperatorGroup (job runs every 1h)

2024-11-06 14:44 UTC, ljeda approved these changes

2024-11-06 14:44 UTC, ljeda commented on controllers/operatorgroup_cleaner.go
> +			logger.Info("Namespace does not exist or is terminating: " + ns + " Namespace marked to remove.")
in my opinion, it would need to be "Namespace marked to be removed" or "Namespace marked for removal". but of course, I'm not the English guru, it just sounds wrong for me ;)

P.S. I know, I'm grumbling :D

2024-11-06 14:44 UTC, ljeda commented on controllers/operatorgroup_cleaner.go
> +	return isActive, nil
why not just
```
return namespace.Status.Phase == corev1.NamespaceActive, nil
```
?

2024-11-07 07:34 UTC, kflorianski-ibm requested changes

2024-11-07 07:34 UTC, kflorianski-ibm commented on controllers/operatorgroup_cleaner.go
>  	}
Shouldn't this just be like so now?
```
if err != nil {
	return false, err
}
```

2024-11-07 08:37 UTC, kflorianski-ibm approved these changes

2024-11-29 16:06 UTC, merged