ILS-248 Add remove field to IBMLicensingDefinition
IBM/ibm-licensing-operator pull request #948
Opened 2024-11-13 13:58 UTC by alicenoknow

This PR adds `remove` field to `IBMLicensingDefinition`. It should work similar to set field but for removing the annotations that may be already present in pod.

2024-11-14 10:54 UTC, tojoos approved these changes
Looks good 👍

2024-11-18 07:50 UTC, kflorianski-ibm requested changes

2024-11-18 07:50 UTC, kflorianski-ibm commented on api/v1/ibmlicensingdefinition_types.go
> +	// List of annotations that will be removed from matched pod
`List of annotations (keys)` or `List of annotation keys` maybe?

2024-11-18 07:50 UTC, kflorianski-ibm commented on api/v1/ibmlicensingdefinition_types.go
> +	Remove []string `json:"remove"`
This change should generate bundle changes, have you ran `make generate manifests bundle`?

2024-11-18 08:54 UTC, pgodowski commented on api/v1/ibmlicensingdefinition_types.go
> +	Remove []string `json:"remove"`
Is this change safe, i.e. do we have preserve unknown fields so that this new field won't be pruned by k8s when older LS CRD is loaded into the cluster?

Also, CRD has to be regerenated, as Kacper wrote.

2024-11-18 12:29 UTC, pgodowski requested changes

2024-11-18 12:29 UTC, pgodowski commented on config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
> +            - remove
When extending CRD, one must not add a new requied field. Where it would fail is the following scenario:

- cluster has already some CRs of Kind: IBMLicensingDefinition, before a new version of LicSvc is installed
- such CR has some fields in, but not `remove` (since such field was not available in older version of License Service)
- License Service is updated, thus CRD definition is upgraded
- K8s will re-validate all the existing CRs in the cluster, against the updated CRD schema - in this case all the already existing CRs will fail such validation
- moreover, if someone wants to add a new IBMLicensingDefinition CR  using older schema when new LicSvc is installed, such operation also fail, since we require additional field.

Long story short: it is ok to add a new field, but not to mark it as required. Yet frankly, why do we actually require this new field in the first place? Perhaps we're just missing `omitempty`?

And then, given we now have both "set" and "remove" - should we actually say that both are optional?

2024-11-18 13:00 UTC, kflorianski-ibm commented on config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
> +            - remove
I agree, both should now be optional. Do we want to enforce at least one is provided in the operand code?

2024-11-20 08:52 UTC, alicenoknow commented on config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
> +            - remove
both fields are now optional, the operand will do the check for both set & remove empty during CR validation along with other checks and log `IbmLicensingDefinition CR <name> is incomplete and cannot be processed`

2024-11-20 09:38 UTC, pgodowski commented on config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
> +            - remove
> log `IbmLicensingDefinition CR <name> is incomplete and cannot be processed`

OK, but pls add more verbose log message, i.e. indicate that one of `set` or `remove` is required - to make sure those who look at the logs are clear what is wrong and what to do / fix

2024-11-20 15:28 UTC, kflorianski-ibm approved these changes

2024-12-04 16:08 UTC, alicenoknow commented
/lgtm

2024-12-04 16:09 UTC, tojoos commented
/lgtm

2024-12-04 16:09 UTC, merged